import type { Model } from '@ank1015/llm-types';

const codexBaseUrl = `https://chatgpt.com/backend-api/codex`;

export const codexModels = {
  'gpt-5.4': {
    id: 'gpt-5.4',
    name: 'GPT-5.4',
    api: 'codex',
    baseUrl: codexBaseUrl,
    reasoning: true,
    input: ['text', 'image', 'file'],
    cost: {
      input: 2.5,
      output: 15,
      cacheRead: 0.25,
      cacheWrite: 0,
    },
    contextWindow: 272000,
    maxTokens: 128000,
    tools: ['function_calling'],
  } satisfies Model<'codex'>,
  'gpt-5.4-mini': {
    id: 'gpt-5.4-mini',
    name: 'GPT-5.4 Mini',
    api: 'codex',
    baseUrl: codexBaseUrl,
    reasoning: true,
    input: ['text', 'image', 'file'],
    cost: {
      input: 0.75,
      output: 4.5,
      cacheRead: 0.075,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 128000,
    tools: ['function_calling'],
  } satisfies Model<'codex'>,
  'gpt-5.3-codex': {
    id: 'gpt-5.3-codex',
    name: 'GPT-5.3 Codex',
    api: 'codex',
    baseUrl: codexBaseUrl,
    reasoning: true,
    input: ['text', 'image', 'file'],
    cost: {
      input: 1.75,
      output: 14,
      cacheRead: 0.175,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 128000,
    tools: ['function_calling'],
    excludeSettings: ['temperature', 'top_p', 'truncation', 'max_output_tokens'],
  } satisfies Model<'codex'>,
  'gpt-5.3-codex-spark': {
    id: 'gpt-5.3-codex-spark',
    name: 'GPT-5.3 Codex Spark',
    api: 'codex',
    baseUrl: codexBaseUrl,
    reasoning: true,
    input: ['text', 'image', 'file'],
    cost: {
      input: 1.75,
      output: 14,
      cacheRead: 0.175,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 128000,
    tools: ['function_calling'],
    excludeSettings: ['temperature', 'top_p', 'truncation', 'max_output_tokens'],
  } satisfies Model<'codex'>,
};
