import type { Model } from '@ank1015/llm-types';

const openaiBaseUrl = `https://api.openai.com/v1`;

export const openaiModels = {
  'gpt-5.4': {
    id: 'gpt-5.4',
    name: 'GPT-5.4',
    api: 'openai',
    baseUrl: openaiBaseUrl,
    reasoning: true,
    input: ['text', 'image', 'file'],
    cost: {
      input: 2.5,
      output: 15,
      cacheRead: 0.25,
      cacheWrite: 0,
    },
    contextWindow: 272000,
    maxTokens: 128000,
    tools: ['function_calling'],
  } satisfies Model<'openai'>,
  'gpt-5.3-codex': {
    id: 'gpt-5.3-codex',
    name: 'GPT-5.3 Codex',
    api: 'openai',
    baseUrl: openaiBaseUrl,
    reasoning: true,
    input: ['text', 'image', 'file'],
    cost: {
      input: 1.75,
      output: 14,
      cacheRead: 0.175,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 128000,
    tools: ['function_calling'],
  } satisfies Model<'openai'>,
  'gpt-5.4-pro': {
    id: 'gpt-5.4-pro',
    name: 'GPT-5.4 Pro',
    api: 'openai',
    baseUrl: openaiBaseUrl,
    reasoning: true,
    input: ['text', 'image', 'file'],
    cost: {
      input: 30,
      output: 180,
      cacheRead: 30,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 128000,
    tools: ['function_calling'],
  } satisfies Model<'openai'>,
  'gpt-5-mini': {
    id: 'gpt-5-mini',
    name: 'GPT-5 Mini',
    api: 'openai',
    baseUrl: openaiBaseUrl,
    reasoning: true,
    input: ['text', 'image', 'file'],
    cost: {
      input: 0.25,
      output: 2,
      cacheRead: 0.025,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 128000,
    tools: ['function_calling'],
  } satisfies Model<'openai'>,
  'gpt-5-nano': {
    id: 'gpt-5-nano',
    name: 'GPT-5 Nano',
    api: 'openai',
    baseUrl: openaiBaseUrl,
    reasoning: true,
    input: ['text', 'image', 'file'],
    cost: {
      input: 0.05,
      output: 0.4,
      cacheRead: 0.005,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 128000,
    tools: ['function_calling'],
  } satisfies Model<'openai'>,
};
