import type { Metadata } from 'next';

import { RootLayout } from '@/components/root';
import '../globals.css';
import { TooltipProvider } from '@/components/ui/tooltip';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Root({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TooltipProvider>
      <RootLayout>
        <div className="relative flex h-full w-full flex-col">{children}</div>
      </RootLayout>
    </TooltipProvider>
  );
}
