import type { Metadata } from 'next';

import { ChatInput } from '@/components/chat/chat-input';
import { Header } from '@/components/header';
import { RootLayout } from '@/components/root';
import { TooltipProvider } from '@/components/ui/tooltip';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Root({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TooltipProvider>
      <RootLayout>
        <div className="relative flex h-full w-full flex-col">
          <Header />
          {children}
        </div>
        <ChatInput />
      </RootLayout>
    </TooltipProvider>
  );
}
